version: '2'
services:
  db:
    image: mysql
    volumes:
    - "./var/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - 3336:3306
  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
    - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
    - ./var/logs/symfony:/var/www/symfony/var/logs
  nginx:
    build: ./docker/nginx
    ports:
    - 8888:80
    volumes_from:
    - php
    volumes:
    - ./var/logs/nginx/:/var/log/nginx
